// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var WithButton$ReactHooksTemplate = require("./WithButton.bs.js");
var DateWithRef$ReactHooksTemplate = require("./DateWithRef.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(DateWithRef$ReactHooksTemplate.make, { }), "index1");

ReactDOMRe.renderToElementWithId(React.createElement(WithButton$ReactHooksTemplate.make, { }), "index2");

/*  Not a pure module */
