// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactReact = require("@denommus/react-react/src/reactReact.bs.js");
var React$ReactFrp = require("react-frp/src/react.js");

var counter = /* record */[/* contents */0];

var match = React$ReactFrp.S[/* create */1](undefined, counter[0]);

var timeF = match[1];

var timeS = match[0];

function timeIncrement(param) {
  counter[0] = counter[0] + 1 | 0;
  return Curry._2(timeF, undefined, counter[0]);
}

var timerId = setInterval(timeIncrement, 1000);

function vdomS(param) {
  return React$ReactFrp.S[/* map */10]((function (param, param$1) {
                return false;
              }), (function (time) {
                var match = time === 1;
                var timeMessage = match ? "second" : "seconds";
                var message = "You\'ve spent " + (String(time) + (" " + (String(timeMessage) + " on this page!")));
                return React.createElement("div", undefined, message);
              }), timeS);
}

function Timer(Props) {
  return ReactReact.componentFromSignal(vdomS, /* () */0);
}

var make = Timer;

exports.counter = counter;
exports.timeS = timeS;
exports.timeF = timeF;
exports.timeIncrement = timeIncrement;
exports.timerId = timerId;
exports.vdomS = vdomS;
exports.make = make;
/* match Not a pure module */
