// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactReact = require("@denommus/react-react/src/reactReact.bs.js");
var Lorem$BsFaker = require("bs-faker/src/Lorem.bs.js");
var React$ReactFrp = require("react-frp/src/react.js");

function vdomS(propsS) {
  return React$ReactFrp.S[/* map */10]((function (param, param$1) {
                return false;
              }), (function (name) {
                console.log("show_name_ref", name);
                var greeting = "The new name is " + (String(name) + "!");
                return React.createElement("p", undefined, greeting);
              }), propsS);
}

function WithButton$ShowName(Props) {
  var name = Props.name;
  return ReactReact.componentFromSignal(vdomS, name);
}

var ShowName = /* module */[
  /* vdomS */vdomS,
  /* make */WithButton$ShowName
];

function getNewName(param) {
  return Lorem$BsFaker.words(3, /* () */0);
}

var name = /* record */[/* contents */Lorem$BsFaker.words(3, /* () */0)];

console.log("name_ref", name);

var match = React$ReactFrp.S[/* create */1](undefined, name[0]);

var nameF = match[1];

var nameS = match[0];

function updateOnClick(param) {
  name[0] = Lorem$BsFaker.words(3, /* () */0);
  return Curry._2(nameF, undefined, name[0]);
}

function vdomS$1(param) {
  return React$ReactFrp.S[/* map */10]((function (param, param$1) {
                return false;
              }), (function (name) {
                return React.createElement("div", undefined, React.createElement(WithButton$ShowName, {
                                name: name
                              }), React.createElement("button", {
                                onClick: (function (_ev) {
                                    return updateOnClick(/* () */0);
                                  })
                              }, "Click for new Name"));
              }), nameS);
}

function WithButton(Props) {
  return ReactReact.componentFromSignal(vdomS$1, /* () */0);
}

var make = WithButton;

exports.ShowName = ShowName;
exports.getNewName = getNewName;
exports.name = name;
exports.nameS = nameS;
exports.nameF = nameF;
exports.updateOnClick = updateOnClick;
exports.vdomS = vdomS$1;
exports.make = make;
/* name Not a pure module */
